version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./quarantineworkout:/quarantineworkout
    command: sh -c "pipenv run python quarantineworkout/manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
